### ISSUE TITLE
Uncaught error when scrolling over dialog with showScrollBar = true 

### ISSUE THREAD

**Issue by gelas7** [What-the-Flutter/wtf_sliding_sheet#26]
Hello! 
I've encountered an unhandled exception while scrolling through the component. The issue seems to arise whenever I try to scroll, with showScrollbar enabled.

**Error:** "The Scrollbar's ScrollController has no ScrollPosition attached."

**Reproducible example:**

```
Future<void> showBottomSheetDialog(
  BuildContext context,
) async {
  final controller = SheetController();

  await showSlidingBottomSheet(
    context,
    builder: (_) {
      return SlidingSheetDialog(
        controller: controller,
        duration: const Duration(milliseconds: 500),
        snapSpec: const SnapSpec(
          snap: true,
          initialSnap: 0.7,
          snappings: [0.3, 0.7],
        ),
        scrollSpec: const ScrollSpec(
          showScrollbar: true,
        ),
        builder: (_, __) => Column(
          children: [
            Container(
              height: 200,
              color: Colors.black,
            ),
            Container(
              height: 700,
              color: Colors.red,
            ),
          ],
        ),
      );
    },
  );
}
```

<img width="500" alt="image" src="https://github.com/What-the-Flutter/wtf_sliding_sheet/assets/36083441/12326822-8d6e-46d0-bdcf-e0bea0a29ce6">

Could you please take a look? Thank you!

**Comment by KirillSergeevich** [comment]
Hey @gelas7!
We fixed this issue https://github.com/What-the-Flutter/wtf_sliding_sheet/pull/28
We'll update the package soon with some other updates
